name = "blog-painel-admin"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist/public"

[env.production]
name = "blog-painel-admin"

[[env.production.routes]]
pattern = "blog-painel.mauromoncao.adv.br/*"
zone_name = "mauromoncao.adv.br"
